{
  "openapi": "3.0.0",
  "info": {
    "title": "Task.io API",
    "description": "API task.io",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/v1"
    }
  ],
  "paths": {
    "/authenticate": {
      "post": {
        "summary": "Autenticação de sessão",
        "description": "Essa rota será responsável por fazer login na aplicação.",
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "comment": {
                  "value": {
                    "username": "admin",
                    "password": "admin"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "username": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "comment": {
                    "value": {
                      "username": "admin"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/sign-out": {
      "post": {
        "summary": "Logoff da aplicação",
        "description": "Essa rota será responsável por fazer logoff na aplicação.",
        "tags": [
          "Sign out"
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "message": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "comment": {
                    "value": {
                      "message": "Logout realizado com sucesso."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "Busca de usuários",
        "description": "Essa rota será responsável por buscar todos os usuários cadastrados.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "userList": {
                    "value": {
                      "users": [
                        {
                          "id": 1,
                          "name": "Pedro",
                          "username": "pedro",
                          "password": "$2a$12$JCeONEkxkfYFkkpiUg2YluzTZz7iSowkslrxPulT2K5MlgjWGiOta",
                          "createdAt": "2024-05-25T16:18:09.442Z",
                          "updatedAt": "2024-05-25T16:18:09.442Z"
                        },
                        {
                          "id": 2,
                          "name": "Marcus",
                          "username": "marcus",
                          "password": "$2a$12$iW4UnIp3EXYDieAC/7dx2OXqljyCVytJ286vursXQML6IZzvJyF7K",
                          "createdAt": "2024-05-25T16:14:16.501Z",
                          "updatedAt": "2024-05-29T02:00:13.629Z"
                        },
                        {
                          "id": 3,
                          "name": "Lucas",
                          "username": "lucas",
                          "password": "$2nb$12$iWa3EXYD2eAC/7dx2-2ljyadCVytad286vunXQv21aL6dZzvJfaV2",
                          "createdAt": "2024-05-26T16:14:16.501Z",
                          "updatedAt": "2024-05-29T07:00:13.629Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Cadastro de usuário",
        "description": "Essa rota será responsável por cadastrar um novo usuário.",
        "tags": [
          "Users"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "items": {
                  "$ref": "#/components/schemas/user"
                }
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "John Doe",
                    "username": "johndoe",
                    "password": "secretpassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Usuário já existente"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "user": {
                        "id": 1,
                        "name": "John Doe",
                        "username": "johndoe",
                        "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                        "updatedAt": "2024-05-29T02:23:43.087Z",
                        "createdAt": "2024-05-29T02:23:43.087Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "summary": "Busca de usuário por ID",
        "description": "Essa rota será responsável por buscar o usuário especificado por ID.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do usuário para busca",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": 1,
                      "name": "John Doe",
                      "username": "johndoe",
                      "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                      "updatedAt": "2024-05-28T02:20:45.087Z",
                      "createdAt": "2024-05-29T02:23:43.087Z"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Atualização de usuário por ID",
        "description": "Esta rota é responsável por atualizar os dados do usuário especificado por ID.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do usuário para atualização",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "items": {
                  "$ref": "#/components/schemas/user"
                }
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "John Doe",
                    "oldPassword": "oldsecretpassword",
                    "newPassword": "newsecretpassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": 1,
                      "name": "John Doe",
                      "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                      "updatedAt": "2024-05-29T02:23:43.087Z",
                      "createdAt": "2024-05-29T02:23:43.087Z"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Exclusão de usuário por ID",
        "description": "Esta rota é responsável por excluir o usuário especificado por ID.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do usuário para exclusão",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "summary": "Busca usuário logado",
        "description": "Essa rota será responsável por buscar o usuário atualmente autenticado.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/user"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": 1,
                      "name": "John Doe",
                      "username": "johndoe",
                      "password": "$2a$12$dPgLyqtAaR8KHN19VD7lcuZaLE1cJUn8OH13tv8DYRlp.oJZLMZVa",
                      "updatedAt": "2024-05-28T02:20:45.087Z",
                      "createdAt": "2024-05-29T02:23:43.087Z"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tasks": {
      "get": {
        "summary": "Busca de tarefas",
        "description": "Essa rota será responsável por buscar todos as tarefas cadastrados.",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhuma tarefa encontrada"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/task"
                  }
                },
                "examples": {
                  "userList": {
                    "value": {
                      "tasks": [
                        {
                          "id": 1,
                          "description": "Estudar",
                          "userId": 1,
                          "completed": true,
                          "createdAt": "2024-06-12T00:31:16.554Z",
                          "updatedAt": "2024-06-12T00:31:16.554Z"
                        },
                        {
                          "id": 2,
                          "description": "Fazer compras",
                          "userId": 2,
                          "completed": false,
                          "createdAt": "2024-06-14T00:31:16.554Z",
                          "updatedAt": "2024-06-14T00:31:16.554Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Cadastro de tarefa",
        "description": "Essa rota será responsável por cadastrar uma nova tarefa.",
        "tags": [
          "Tasks"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "items": {
                  "$ref": "#/components/schemas/task"
                }
              },
              "examples": {
                "user": {
                  "value": {
                    "description": "Tarefa 1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/task"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "task": {
                        "id": 1,
                        "description": "Tarefa 1",
                        "userId": 1,
                        "completed": false,
                        "updatedAt": "2024-06-13T23:34:25.626Z",
                        "createdAt": "2024-06-13T23:34:25.626Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tasks/{taskId}": {
      "get": {
        "summary": "Busca de tarefa por ID",
        "description": "Essa rota será responsável por buscar a tarefa especificada por ID.",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "schema": {
              "type": "integer"
            },
            "description": "ID da tarefa para busca",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhuma tarefa encontrada"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/task"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "task": {
                        "id": 1,
                        "description": "Tarefa 1",
                        "userId": 1,
                        "completed": false,
                        "updatedAt": "2024-06-13T23:34:25.626Z",
                        "createdAt": "2024-06-13T23:34:25.626Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Atualização de tarefa por ID",
        "description": "Esta rota é responsável por atualizar os dados da tarefa especificada por ID.",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "schema": {
              "type": "integer"
            },
            "description": "ID da tarefa para atualização",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "items": {
                  "$ref": "#/components/schemas/task"
                }
              },
              "examples": {
                "user": {
                  "value": {
                    "description": "Tarefa atualizada",
                    "completed": "true"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhuma tarefa encontrada"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/task"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "id": 1,
                      "description": "Tarefa atualizada",
                      "userId": 1,
                      "completed": true,
                      "createdAt": "2024-06-14T01:09:59.333Z",
                      "updatedAt": "2024-06-14T01:09:59.333Z"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Exclusão de tarefa por ID",
        "description": "Esta rota é responsável por excluir a tarefa especificado por ID.",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "schema": {
              "type": "integer"
            },
            "description": "ID da tarefa para exclusão",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhuma tarefa encontrada"
          },
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/tasks/my": {
      "get": {
        "summary": "Busca tarefas do usuário logado",
        "description": "Essa rota será responsável por buscar as tarefas do usuário atualmente autenticado.",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum usuário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/task"
                  }
                },
                "examples": {
                  "user": {
                    "value": {
                      "tasks": [
                        {
                          "id": 1,
                          "description": "Tarefa 1",
                          "userId": 1,
                          "completed": false,
                          "createdAt": "2024-06-14T00:31:16.554Z",
                          "updatedAt": "2024-06-14T00:31:16.554Z"
                        },
                        {
                          "id": 2,
                          "description": "Tarefa 2",
                          "userId": 1,
                          "completed": false,
                          "createdAt": "2024-06-14T01:09:59.333Z",
                          "updatedAt": "2024-06-14T01:09:59.333Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/comments": {
      "post": {
        "summary": "Cadastro de comentário",
        "description": "Essa rota será responsável por cadastrar um novo comentário.",
        "tags": [
          "Comments"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "comment": {
                  "value": {
                    "content": "Comentário 1",
                    "taskId": 1
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "content": {
                        "type": "string"
                      },
                      "createdAt": {
                        "type": "string"
                      },
                      "updatedAt": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "comment": {
                    "value": {
                      "comment": {
                        "id": 1,
                        "content": "Comentário 1",
                        "userId": 1,
                        "taskId": 1,
                        "createdAt": "2024-05-29T02:23:43.087Z",
                        "updatedAt": "2024-05-29T02:23:43.087Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/comments/{taskId}": {
      "get": {
        "summary": "Busca de comentários por ID da tarefa",
        "description": "Essa rota será responsável por buscar todos os comentários da tarefa especificada por ID.",
        "tags": [
          "Comments"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "schema": {
              "type": "integer"
            },
            "description": "ID da tarefa para busca de comentários",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum comentário encontrado"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "content": {
                        "type": "string"
                      },
                      "createdAt": {
                        "type": "string"
                      },
                      "updatedAt": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "commentList": {
                    "value": {
                      "comments": [
                        {
                          "id": 1,
                          "content": "Comentário 1",
                          "userId": 1,
                          "taskId": 1,
                          "createdAt": "2024-05-29T02:23:43.087Z",
                          "updatedAt": "2024-05-29T02:23:43.087Z"
                        },
                        {
                          "id": 2,
                          "content": "Comentário 2",
                          "userId": 2,
                          "taskId": 2,
                          "createdAt": "2024-05-29T02:23:43.087Z",
                          "updatedAt": "2024-05-29T02:23:43.087Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/comments/{commentId}": {
      "delete": {
        "summary": "Exclusão de comentário por ID",
        "description": "Esta rota é responsável por excluir o comentário especificado por ID da tarefa e ID do comentário.",
        "tags": [
          "Comments"
        ],
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "taskId",
            "schema": {
              "type": "integer"
            },
            "description": "ID da tarefa para exclusão do comentário",
            "required": true
          },
          {
            "in": "path",
            "name": "commentId",
            "schema": {
              "type": "integer"
            },
            "description": "ID do comentário para exclusão",
            "required": true
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Nenhum comentário encontrado"
          },
          "204": {
            "description": "No Content"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "task": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "description": {
            "type": "string"
          },
          "userId": {
            "type": "number"
          },
          "completed": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      },
      "comments": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "comment": {
            "type": "string"
          },
          "userId": {
            "type": "integer"
          },
          "taskId": {
            "type": "integer"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "cookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "access_token"
      }
    }
  }
}